const stock_actualizado = [
  { modelo: 'Air forcé 1 blancas', talles: [{"talle": 36, "stock": 1}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 3}, {"talle": 39, "stock": 3}, {"talle": 40, "stock": 10}, {"talle": 41, "stock": 9}, {"talle": 42, "stock": 7}, {"talle": 43, "stock": 3}, {"talle": 44, "stock": 3}], foto: 'Fotos/Air forcé 1 blancas.jpeg' },
  { modelo: 'Vans KNU clasicas', talles: [{"talle": 34, "stock": 4}, {"talle": 43, "stock": 1}], foto: 'Fotos/Vans KNU clasicas.jpeg' },
  { modelo: 'Panda sb dunk', talles: [{"talle": 35, "stock": 3}, {"talle": 37, "stock": 5}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 2}, {"talle": 43, "stock": 16}], foto: 'Fotos/Panda sb dunk.jpeg' },
  { modelo: 'Adidas forum blancas', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 3}, {"talle": 37, "stock": 7}, {"talle": 39, "stock": 2}, {"talle": 40, "stock": 6}, {"talle": 42, "stock": 1}, {"talle": 43, "stock": 2}], foto: 'Fotos/Adidas forum blancas.jpeg' },
  { modelo: 'New balance 530 running', talles: [{"talle": 42, "stock": 2}, {"talle": 43, "stock": 3}, {"talle": 44, "stock": 2}, {"talle": 45, "stock": 2}], foto: 'Fotos/New balance 530 running.jpeg' },
  { modelo: 'Super star black', talles: [{"talle": 34, "stock": 2}, {"talle": 35, "stock": 2}, {"talle": 36, "stock": 2}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 2}, {"talle": 40, "stock": 5}, {"talle": 41, "stock": 9}, {"talle": 42, "stock": 8}, {"talle": 43, "stock": 4}, {"talle": 44, "stock": 3}], foto: 'Fotos/Super star black.jpeg' },
  { modelo: 'Puma 180 WHITE', talles: [{"talle": 34, "stock": 5}, {"talle": 35, "stock": 4}], foto: 'Fotos/Puma 180 WHITE.jpeg' },
  { modelo: 'Air forcé suela celeste', talles: [{"talle": 41, "stock": 1}, {"talle": 43, "stock": 3}], foto: 'Fotos/Air forcé suela celeste.jpeg' },
  { modelo: 'Adidas forum Gelo', talles: [{"talle": 40, "stock": 5}, {"talle": 41, "stock": 3}], foto: 'Fotos/Adidas forum Gelo.jpeg' },
  { modelo: 'Sb dunk gris', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 5}, {"talle": 43, "stock": 4}, {"talle": 44, "stock": 1}], foto: 'Fotos/Sb dunk gris.jpeg' },
  { modelo: 'Super star clásic', talles: [{"talle": 34, "stock": 2}, {"talle": 35, "stock": 2}, {"talle": 36, "stock": 1}, {"talle": 39, "stock": 3}, {"talle": 40, "stock": 5}, {"talle": 41, "stock": 5}, {"talle": 42, "stock": 7}, {"talle": 43, "stock": 5}, {"talle": 44, "stock": 2}], foto: 'Fotos/Super star clásic.jpeg' },
  { modelo: 'Jordan botitas 1 vermelho', talles: [{"talle": 40, "stock": 2}, {"talle": 41, "stock": 2}, {"talle": 42, "stock": 2}, {"talle": 43, "stock": 1}, {"talle": 44, "stock": 1}], foto: 'Fotos/Jordan botitas 1 vermelho.jpeg' },
  { modelo: 'Dunk pombo', talles: [{"talle": 40, "stock": 1}, {"talle": 41, "stock": 5}, {"talle": 42, "stock": 7}, {"talle": 43, "stock": 8}, {"talle": 44, "stock": 4}, {"talle": 45, "stock": 1}], foto: 'Fotos/Dunk pombo.jpeg' },
  { modelo: 'Jordan retro 4 pintita', talles: [{"talle": 43, "stock": 3}, {"talle": 44, "stock": 4}], foto: 'Fotos/Jordan retro 4 pintita.jpeg' },
  { modelo: 'Adidas forum blanco Preto', talles: [{"talle": 35, "stock": 2}, {"talle": 36, "stock": 1}, {"talle": 38, "stock": 1}, {"talle": 39, "stock": 6}, {"talle": 40, "stock": 5}, {"talle": 41, "stock": 4}, {"talle": 43, "stock": 1}], foto: 'Fotos/Adidas forum blanco Preto.jpeg' },
  { modelo: 'Jordan 1 botitas pink', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 3}, {"talle": 37, "stock": 6}, {"talle": 38, "stock": 6}, {"talle": 39, "stock": 4}, {"talle": 40, "stock": 8}], foto: 'Fotos/Jordan 1 botitas pink.jpeg' },
  { modelo: 'Air forcé exclusivas white', talles: [{"talle": 36, "stock": 1}, {"talle": 37, "stock": 1}, {"talle": 39, "stock": 4}, {"talle": 40, "stock": 1}, {"talle": 41, "stock": 7}, {"talle": 42, "stock": 5}, {"talle": 43, "stock": 10}, {"talle": 44, "stock": 2}], foto: 'Fotos/Air forcé exclusivas white.jpeg' },
  { modelo: 'Puma 180 flamingo', talles: [{"talle": 34, "stock": 6}, {"talle": 35, "stock": 7}, {"talle": 36, "stock": 5}, {"talle": 38, "stock": 2}], foto: 'Fotos/Puma 180 flamingo.jpeg' },
  { modelo: 'Air forcé 1 total black', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 2}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 4}, {"talle": 38, "stock": 5}, {"talle": 40, "stock": 2}, {"talle": 42, "stock": 1}], foto: 'Fotos/Air forcé 1 total black.jpeg' },
  { modelo: 'Jordan retro 4 pink', talles: [{"talle": 39, "stock": 3}], foto: 'Fotos/Jordan retro 4 pink.jpeg' },
  { modelo: 'Jordan retro 4 /total black', talles: [{"talle": 37, "stock": 3}, {"talle": 38, "stock": 1}, {"talle": 39, "stock": 2}, {"talle": 41, "stock": 1}, {"talle": 42, "stock": 1}, {"talle": 43, "stock": 3}, {"talle": 44, "stock": 3}], foto: 'Fotos/Jordan retro 4 total black.jpeg' },
  { modelo: 'NB 530 blanca /azul', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 5}, {"talle": 36, "stock": 8}, {"talle": 37, "stock": 10}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 4}, {"talle": 40, "stock": 2}, {"talle": 41, "stock": 4}, {"talle": 42, "stock": 6}, {"talle": 43, "stock": 4}, {"talle": 44, "stock": 2}], foto: 'Fotos/NB 530 blanca azul.jpeg' },
  { modelo: 'Dunk total black', talles: [{"talle": 39, "stock": 2}, {"talle": 40, "stock": 2}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 5}, {"talle": 43, "stock": 5}, {"talle": 44, "stock": 3}], foto: 'Fotos/Dunk total black.jpeg' },
  { modelo: 'Dunk glistter celeste', talles: [{"talle": 37, "stock": 2}], foto: 'Fotos/Dunk glistter celeste.jpeg' },
  { modelo: 'Deportivas fit black', talles: [{"talle": 35, "stock": 4}, {"talle": 36, "stock": 3}, {"talle": 37, "stock": 1}, {"talle": 38, "stock": 4}, {"talle": 39, "stock": 3}, {"talle": 40, "stock": 4}, {"talle": 41, "stock": 8}, {"talle": 42, "stock": 8}, {"talle": 43, "stock": 3}, {"talle": 44, "stock": 3}], foto: 'Fotos/Deportivas fit black.jpeg' },
  { modelo: 'Jordan low CHAROL', talles: [{"talle": 43, "stock": 1}], foto: 'Fotos/Jordan low CHAROL.jpeg' },
  { modelo: 'New balance 9060 suela rosa', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 1}], foto: 'Fotos/New balance 9060 suela rosa.jpeg' },
  { modelo: 'Vans Haylan 01', talles: [{"talle": 40, "stock": 1}], foto: 'Fotos/Vans Haylan 01.jpeg' },
  { modelo: 'Vans HAYLAN NOVA', talles: [{"talle": 36, "stock": 2}, {"talle": 38, "stock": 1}], foto: 'Fotos/Vans HAYLAN NOVA.jpeg' },
  { modelo: 'Dunk glitter rosa', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 4}, {"talle": 38, "stock": 3}, {"talle": 39, "stock": 2}, {"talle": 40, "stock": 1}], foto: 'Fotos/Dunk glitter rosa.jpeg' },
  { modelo: 'Sb dunk pipa negra', talles: [{"talle": 36, "stock": 2}, {"talle": 41, "stock": 1}, {"talle": 43, "stock": 3}, {"talle": 44, "stock": 1}], foto: 'Fotos/Sb dunk pipa negra.jpeg' },
  { modelo: 'Sb dunk glitter beige', talles: [{"talle": 37, "stock": 4}, {"talle": 38, "stock": 4}, {"talle": 40, "stock": 1}], foto: 'Fotos/Sb dunk glitter beige.jpeg' },
  { modelo: 'NB 530 blanca/negro', talles: [{"talle": 35, "stock": 1}, {"talle": 37, "stock": 2}, {"talle": 39, "stock": 2}, {"talle": 40, "stock": 4}], foto: 'Fotos/NB 530 blanca negro.jpeg' },
  { modelo: 'Nike shox white', talles: [{"talle": 39, "stock": 2}, {"talle": 40, "stock": 2}, {"talle": 41, "stock": 5}, {"talle": 42, "stock": 9}, {"talle": 43, "stock": 11}, {"talle": 44, "stock": 1}], foto: 'Fotos/Nike shox white.jpeg' },
  { modelo: 'Shox black', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 1}, {"talle": 37, "stock": 3}, {"talle": 39, "stock": 1}, {"talle": 40, "stock": 4}, {"talle": 41, "stock": 6}, {"talle": 42, "stock": 5}, {"talle": 43, "stock": 3}, {"talle": 44, "stock": 2}], foto: 'Fotos/Shox black.jpeg' },
  { modelo: 'Adidas fórum verde summer', talles: [{"talle": 35, "stock": 1}, {"talle": 40, "stock": 1}], foto: 'Fotos/Adidas fórum verde summer.jpeg' },
  { modelo: 'Jordan 1 verniz', talles: [{"talle": 34, "stock": 2}, {"talle": 35, "stock": 4}, {"talle": 36, "stock": 7}, {"talle": 37, "stock": 6}, {"talle": 38, "stock": 5}, {"talle": 39, "stock": 7}, {"talle": 40, "stock": 6}, {"talle": 41, "stock": 6}, {"talle": 42, "stock": 4}, {"talle": 43, "stock": 2}, {"talle": 44, "stock": 1}], foto: 'Fotos/Jordan 1 verniz.jpeg' },
  { modelo: 'Jordan retro 4 panda', talles: [{"talle": 39, "stock": 1}, {"talle": 40, "stock": 5}, {"talle": 41, "stock": 4}, {"talle": 42, "stock": 1}, {"talle": 43, "stock": 2}], foto: 'Fotos/Jordan retro 4 panda.jpeg' },
  { modelo: 'Air force 1 blanca /pipa gris', talles: [{"talle": 36, "stock": 2}, {"talle": 40, "stock": 1}, {"talle": 42, "stock": 1}], foto: 'Fotos/Air force 1 blanca pipa gris.jpeg' },
  { modelo: 'Jordan low 1 DIAMOND', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 2}, {"talle": 38, "stock": 3}, {"talle": 39, "stock": 2}, {"talle": 40, "stock": 1}], foto: 'Fotos/Jordan low 1 DIAMOND.jpeg' },
  { modelo: 'Samba Classic', talles: [{"talle": 43, "stock": 3}, {"talle": 44, "stock": 1}], foto: 'Fotos/Samba Classic.jpeg' },
  { modelo: 'Vans haylan black', talles: [{"talle": 36, "stock": 1}], foto: 'Fotos/Vans haylan black.jpeg' },
  { modelo: 'Deportivas fit white', talles: [{"talle": 35, "stock": 2}, {"talle": 36, "stock": 1}], foto: 'Fotos/Deportivas fit white.jpeg' },
  { modelo: 'Super star rosa', talles: [{"talle": 40, "stock": 1}], foto: 'Fotos/Super star rosa.jpeg' },
  { modelo: 'New balance ABZORB BEGE', talles: [{"talle": 34, "stock": 1}, {"talle": 36, "stock": 2}], foto: 'Fotos/New balance ABZORB BEGE.jpeg' },
  { modelo: 'Jordan low VERNIZ /AZUL', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 2}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 3}], foto: 'Fotos/Jordan low VERNIZ AZUL.jpeg' },
  { modelo: 'Vans Haylan beige', talles: [{"talle": 37, "stock": 2}, {"talle": 38, "stock": 1}, {"talle": 39, "stock": 2}, {"talle": 40, "stock": 7}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 6}, {"talle": 43, "stock": 3}], foto: 'Fotos/Vans Haylan beige.jpeg' },
  { modelo: 'Súper star brillo', talles: [{"talle": 41, "stock": 1}], foto: 'Fotos/Súper star brillo.jpeg' },
  { modelo: 'Jordan 1 azules', talles: [{"talle": 35, "stock": 2}, {"talle": 37, "stock": 3}], foto: 'Fotos/Jordan 1 azules.jpeg' },
  { modelo: 'Sb dunk cinza/preto', talles: [{"talle": 44, "stock": 2}], foto: 'Fotos/Sb dunk cinza preto.jpeg' },
  { modelo: 'Jordan 1 branco / pink', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 1}, {"talle": 37, "stock": 1}, {"talle": 38, "stock": 3}], foto: 'Fotos/Jordan 1 branco pink.jpeg' },
  { modelo: 'ABZORB marrones', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 6}, {"talle": 36, "stock": 9}, {"talle": 37, "stock": 6}, {"talle": 38, "stock": 4}, {"talle": 39, "stock": 3}], foto: 'Fotos/ABZORB marrones.jpeg' },
  { modelo: 'Jordan low pombo', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 2}, {"talle": 36, "stock": 3}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 1}], foto: 'Fotos/Jordan low pombo.jpeg' },
  { modelo: 'Adidas boas negra', talles: [{"talle": 36, "stock": 2}, {"talle": 37, "stock": 2}, {"talle": 39, "stock": 1}, {"talle": 40, "stock": 2}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 3}, {"talle": 43, "stock": 2}, {"talle": 44, "stock": 1}], foto: 'Fotos/Adidas boas negra.jpeg' },
  { modelo: 'Jordan botitas charol', talles: [{"talle": 44, "stock": 1}], foto: 'Fotos/Jordan botitas charol.jpeg' },
  { modelo: 'Dunk combinada celeste', talles: [{"talle": 39, "stock": 1}, {"talle": 43, "stock": 3}], foto: 'Fotos/Dunk combinada celeste.jpeg' },
  { modelo: 'Shox tapón rojo', talles: [{"talle": 39, "stock": 3}, {"talle": 40, "stock": 6}, {"talle": 41, "stock": 8}, {"talle": 42, "stock": 8}, {"talle": 43, "stock": 8}, {"talle": 44, "stock": 3}], foto: 'Fotos/Shox tapón rojo.jpeg' },
  { modelo: 'Sb dunk platino', talles: [{"talle": 36, "stock": 2}, {"talle": 37, "stock": 1}, {"talle": 38, "stock": 3}, {"talle": 39, "stock": 1}, {"talle": 40, "stock": 1}], foto: 'Fotos/Sb dunk platino.jpeg' },
  { modelo: 'Vans Haylan bonitas', talles: [{"talle": 35, "stock": 1}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 4}, {"talle": 40, "stock": 1}], foto: 'Fotos/Vans Haylan bonitas.jpeg' },
  { modelo: 'Jordan low brillo', talles: [{"talle": 36, "stock": 2}, {"talle": 40, "stock": 1}], foto: 'Fotos/Jordan low brillo.jpeg' },
  { modelo: 'Shox preto/prata', talles: [{"talle": 44, "stock": 1}], foto: 'Fotos/Shox preto prata.jpeg' },
  { modelo: 'Nike Jordan Pink', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 3}, {"talle": 36, "stock": 4}, {"talle": 37, "stock": 4}], foto: 'Fotos/Nike Jordan Pink.jpeg' },
  { modelo: 'Puma bmw', talles: [{"talle": 35, "stock": 1}], foto: 'Fotos/Puma bmw.jpeg' },
  { modelo: 'Súper star brillo perla', talles: [{"talle": 36, "stock": 1}, {"talle": 37, "stock": 2}, {"talle": 38, "stock": 3}, {"talle": 39, "stock": 3}, {"talle": 40, "stock": 2}], foto: 'Fotos/Súper star brillo perla.jpeg' },
  { modelo: 'Dunk blanco/marinho', talles: [{"talle": 43, "stock": 1}], foto: 'Fotos/Dunk blanco marinho.jpeg' },
  { modelo: 'Jordan Diamond pipa blanca', talles: [{"talle": 35, "stock": 1}], foto: 'Fotos/Jordan Diamond pipa blanca.jpeg' },
  { modelo: 'Botitas Vans', talles: [{"talle": 35, "stock": 1}, {"talle": 37, "stock": 1}, {"talle": 39, "stock": 1}, {"talle": 40, "stock": 1}], foto: 'Fotos/Botitas Vans.jpeg' },
  { modelo: 'Dunk jean marrón', talles: [{"talle": 39, "stock": 2}, {"talle": 40, "stock": 1}, {"talle": 41, "stock": 4}, {"talle": 42, "stock": 3}, {"talle": 43, "stock": 4}], foto: 'Fotos/Dunk jean marrón.jpeg' },
  { modelo: 'Sb Dunk grafito', talles: [{"talle": 43, "stock": 1}], foto: 'Fotos/Sb Dunk grafito.jpeg' },
  { modelo: 'Vans Haylan azul', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 1}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 1}], foto: 'Fotos/Vans Haylan azul.jpeg' },
  { modelo: 'Jordan low suela transparente', talles: [{"talle": 44, "stock": 1}], foto: 'Fotos/Jordan low suela transparente.jpeg' },
  { modelo: 'ABZORB claritas', talles: [{"talle": 34, "stock": 2}, {"talle": 36, "stock": 2}], foto: 'Fotos/ABZORB claritas.jpeg' },
  { modelo: 'Air forcé negras medias', talles: [{"talle": 37, "stock": 4}, {"talle": 38, "stock": 4}, {"talle": 40, "stock": 1}, {"talle": 42, "stock": 3}, {"talle": 43, "stock": 2}, {"talle": 44, "stock": 1}], foto: 'Fotos/Air forcé negras medias.jpeg' },
  { modelo: 'Jordan 1 black/ vermelo', talles: [{"talle": 35, "stock": 1}, {"talle": 38, "stock": 1}, {"talle": 40, "stock": 1}, {"talle": 42, "stock": 2}, {"talle": 43, "stock": 1}], foto: 'Fotos/Jordan 1 black vermelo.jpeg' },
  { modelo: 'Botitas Jordan niño', talles: [{"talle": 26, "stock": 1}], foto: 'Fotos/Botitas Jordan niño.jpeg' },
  { modelo: 'Shox tapón rosa', talles: [{"talle": 37, "stock": 2}], foto: 'Fotos/Shox tapón rosa.jpeg' },
  { modelo: 'Vans Haylan 01 LUXO', talles: [{"talle": 40, "stock": 2}, {"talle": 42, "stock": 2}, {"talle": 43, "stock": 2}, {"talle": 44, "stock": 2}], foto: 'Fotos/Vans Haylan 01 LUXO.jpeg' },
  { modelo: 'Air forcé carbono', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 3}, {"talle": 39, "stock": 2}, {"talle": 40, "stock": 1}], foto: 'Fotos/Air forcé carbono.jpeg' },
  { modelo: 'Samba total black', talles: [{"talle": 36, "stock": 2}], foto: 'Fotos/Samba total black.jpeg' },
  { modelo: 'Sb dunk polar', talles: [{"talle": 36, "stock": 2}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 3}, {"talle": 39, "stock": 3}, {"talle": 40, "stock": 1}], foto: 'Fotos/Sb dunk polar.jpeg' },
  { modelo: 'Adidas 2000 BLACK', talles: [{"talle": 44, "stock": 1}], foto: 'Fotos/Adidas 2000 BLACK.jpeg' },
  { modelo: 'Vans Haylan pink', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 5}, {"talle": 38, "stock": 10}, {"talle": 39, "stock": 4}, {"talle": 40, "stock": 2}], foto: 'Fotos/Vans Haylan pink.jpeg' },
  { modelo: 'ABZORB negras', talles: [{"talle": 35, "stock": 1}], foto: 'Fotos/ABZORB negras.jpeg' },
  { modelo: 'Retro 4 gelo', talles: [{"talle": 43, "stock": 1}], foto: 'Fotos/Retro 4 gelo.jpeg' },
  { modelo: 'Vans Haylan grafite', talles: [{"talle": 43, "stock": 2}], foto: 'Fotos/Vans Haylan grafite.jpeg' },
  { modelo: 'Air forcé charol brillante', talles: [{"talle": 44, "stock": 1}], foto: 'Fotos/Air forcé charol brillante.jpeg' },
  { modelo: 'Botitas niños azul', talles: [{"talle": 26, "stock": 2}, {"talle": 28, "stock": 1}, {"talle": 30, "stock": 2}, {"talle": 31, "stock": 2}, {"talle": 32, "stock": 2}, {"talle": 33, "stock": 2}], foto: 'Fotos/Botitas niños azul.jpeg' },
  { modelo: 'Adidas 2000 royal', talles: [{"talle": 41, "stock": 1}, {"talle": 43, "stock": 1}], foto: 'Fotos/Adidas 2000 royal.jpeg' },
  { modelo: 'Jordan 11 negra/blanca', talles: [{"talle": 41, "stock": 2}], foto: 'Fotos/Jordan 11 negra blanca.jpeg' },
  { modelo: 'Vans Haylan marron', talles: [{"talle": 38, "stock": 2}], foto: 'Fotos/Vans Haylan marron.jpeg' },
  { modelo: 'Puma 180 White/gris', talles: [{"talle": 40, "stock": 2}, {"talle": 42, "stock": 2}], foto: 'Fotos/Puma 180 White gris.jpeg' },
  { modelo: 'New balance 530 marrones', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 1}, {"talle": 37, "stock": 1}, {"talle": 38, "stock": 3}, {"talle": 39, "stock": 3}], foto: 'Fotos/New balance 530 marrones.jpeg' },
  { modelo: 'Jordan 1 verde / naranja', talles: [{"talle": 41, "stock": 2}, {"talle": 43, "stock": 2}, {"talle": 44, "stock": 1}], foto: 'Fotos/Jordan 1 verde naranja.jpeg' },
  { modelo: 'Nike mind gris', talles: [{"talle": 40, "stock": 2}, {"talle": 41, "stock": 1}, {"talle": 43, "stock": 2}], foto: 'Fotos/Nike mind gris.jpeg' },
  { modelo: 'Sb Dunk VINO', talles: [{"talle": 39, "stock": 1}, {"talle": 40, "stock": 1}, {"talle": 42, "stock": 3}], foto: 'Fotos/Sb Dunk VINO.jpeg' },
  { modelo: 'Shox tapón celeste', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 3}, {"talle": 40, "stock": 2}, {"talle": 41, "stock": 2}, {"talle": 42, "stock": 2}, {"talle": 43, "stock": 1}], foto: 'Fotos/Shox tapón celeste.jpeg' },
  { modelo: 'Botita niño panda', talles: [{"talle": 26, "stock": 1}, {"talle": 27, "stock": 3}, {"talle": 28, "stock": 1}, {"talle": 29, "stock": 3}, {"talle": 31, "stock": 3}, {"talle": 33, "stock": 3}], foto: 'Fotos/Botita niño panda.jpeg' },
  { modelo: 'Nb ABZORB white', talles: [{"talle": 35, "stock": 2}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 2}], foto: 'Fotos/Nb ABZORB white.jpeg' },
  { modelo: 'Jordan 11 suela azul', talles: [{"talle": 39, "stock": 1}, {"talle": 40, "stock": 2}, {"talle": 42, "stock": 3}, {"talle": 43, "stock": 1}], foto: 'Fotos/Jordan 11 suela azul.jpeg' },
  { modelo: 'Botitas negras niño', talles: [{"talle": 26, "stock": 2}, {"talle": 27, "stock": 2}, {"talle": 28, "stock": 2}, {"talle": 29, "stock": 3}, {"talle": 30, "stock": 2}, {"talle": 31, "stock": 3}, {"talle": 32, "stock": 1}, {"talle": 33, "stock": 1}], foto: 'Fotos/Botitas negras niño.jpeg' },
  { modelo: 'Jordan 1 brillosa', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 1}, {"talle": 37, "stock": 2}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 1}, {"talle": 40, "stock": 1}], foto: 'Fotos/Jordan 1 brillosa.jpeg' },
  { modelo: 'Air forcé black brillo', talles: [{"talle": 35, "stock": 2}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 2}, {"talle": 38, "stock": 2}], foto: 'Fotos/Air forcé black brillo.jpeg' },
  { modelo: 'NB celeste 9060', talles: [{"talle": 35, "stock": 1}], foto: 'Fotos/NB celeste 9060.jpeg' },
  { modelo: 'Vans Haylan black luxo', talles: [{"talle": 40, "stock": 1}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 1}, {"talle": 43, "stock": 2}, {"talle": 44, "stock": 1}], foto: 'Fotos/Vans Haylan black luxo.jpeg' },
  { modelo: 'Vans Haylan azul luxo', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 2}, {"talle": 40, "stock": 1}], foto: 'Fotos/Vans Haylan azul luxo.jpeg' },
  { modelo: 'Shox tapón dorada', talles: [{"talle": 39, "stock": 1}, {"talle": 40, "stock": 1}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 3}, {"talle": 43, "stock": 2}], foto: 'Fotos/Shox tapón dorada.jpeg' },
  { modelo: 'Dunk preto/blanco', talles: [{"talle": 39, "stock": 1}, {"talle": 40, "stock": 1}, {"talle": 41, "stock": 2}, {"talle": 42, "stock": 2}, {"talle": 43, "stock": 2}, {"talle": 44, "stock": 1}], foto: 'Fotos/Dunk preto blanco.jpeg' },
  { modelo: 'Jordan 1 beige tornasol', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 2}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 1}], foto: 'Fotos/Jordan 1 beige tornasol.jpeg' },
  { modelo: 'Dunk marinho red', talles: [{"talle": 39, "stock": 1}, {"talle": 40, "stock": 1}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 3}, {"talle": 43, "stock": 2}, {"talle": 44, "stock": 1}], foto: 'Fotos/Dunk marinho red.jpeg' },
  { modelo: 'Jordan low glister', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 4}, {"talle": 36, "stock": 6}, {"talle": 37, "stock": 6}, {"talle": 38, "stock": 4}, {"talle": 39, "stock": 2}], foto: 'Fotos/Jordan low glister.jpeg' },
  { modelo: 'Adidas 2000 white', talles: [{"talle": 39, "stock": 1}, {"talle": 40, "stock": 2}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 2}, {"talle": 43, "stock": 2}, {"talle": 44, "stock": 1}], foto: 'Fotos/Adidas 2000 white.jpeg' },
  { modelo: 'Dunk verde oliva', talles: [{"talle": 41, "stock": 2}, {"talle": 42, "stock": 3}, {"talle": 43, "stock": 3}, {"talle": 44, "stock": 2}, {"talle": 45, "stock": 1}], foto: 'Fotos/Dunk verde oliva.jpeg' },
  { modelo: 'Dunk gris gamusa', talles: [{"talle": 39, "stock": 1}, {"talle": 40, "stock": 1}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 3}, {"talle": 43, "stock": 2}, {"talle": 44, "stock": 1}], foto: 'Fotos/Dunk gris gamusa.jpeg' },
  { modelo: 'Jordan 1 celeste / verniz', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 2}, {"talle": 36, "stock": 3}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 1}], foto: 'Fotos/Jordan 1 celeste verniz.jpeg' },
  { modelo: 'Jordan 1 bordo/rosa', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 2}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 1}], foto: 'Fotos/Jordan 1 bordo rosa.jpeg' },
];
