const stock_zapatillas = [
  { modelo: 'Air forcé 1 blancas', talles: [{"talle": 38, "stock": 3}, {"talle": 42, "stock": 1}, {"talle": 44, "stock": 1}], foto: 'Fotos/Air forcé 1 blancas.jpeg' },
  { modelo: 'Vans KNU clasicas', talles: [{"talle": 34, "stock": 8}, {"talle": 35, "stock": 5}, {"talle": 36, "stock": 4}, {"talle": 38, "stock": 3}, {"talle": 41, "stock": 1}, {"talle": 42, "stock": 2}, {"talle": 43, "stock": 1}], foto: 'Fotos/Vans KNU clasicas.jpeg' },
  { modelo: 'Panda sb dunk', talles: [{"talle": 35, "stock": 3}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 4}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 2}, {"talle": 40, "stock": 6}, {"talle": 41, "stock": 1}], foto: 'Fotos/Panda sb dunk.jpeg' },
  { modelo: 'Puma 180 WHITE', talles: [{"talle": 35, "stock": 6}, {"talle": 36, "stock": 4}, {"talle": 37, "stock": 14}, {"talle": 38, "stock": 14}, {"talle": 39, "stock": 8}, {"talle": 40, "stock": 1}, {"talle": 42, "stock": 4}, {"talle": 43, "stock": 3}, {"talle": 44, "stock": 1}], foto: 'Fotos/Puma 180 WHITE.jpeg' },
  { modelo: 'Super star black', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 9}, {"talle": 37, "stock": 6}, {"talle": 38, "stock": 7}, {"talle": 39, "stock": 7}, {"talle": 40, "stock": 1}, {"talle": 43, "stock": 1}, {"talle": 44, "stock": 2}], foto: 'Fotos/Super star black.jpeg' },
  { modelo: 'Super star clásic', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 2}, {"talle": 36, "stock": 2}, {"talle": 44, "stock": 2}], foto: 'Fotos/Super star clásic.jpeg' },
  { modelo: 'Air forcé suela celeste', talles: [{"talle": 39, "stock": 1}, {"talle": 40, "stock": 1}, {"talle": 41, "stock": 4}, {"talle": 42, "stock": 5}, {"talle": 43, "stock": 3}, {"talle": 44, "stock": 1}], foto: 'Fotos/Air forcé suela celeste.jpeg' },
  { modelo: 'Sb dunk gris', talles: [{"talle": 35, "stock": 1}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 5}, {"talle": 43, "stock": 2}], foto: 'Fotos/Sb dunk gris.jpeg' },
  { modelo: 'Dunk bordo', talles: [{"talle": 38, "stock": 4}, {"talle": 39, "stock": 4}], foto: 'Fotos/Dunk bordo.jpeg' },
  { modelo: 'Deportivas fit black', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 1}, {"talle": 40, "stock": 2}, {"talle": 41, "stock": 1}, {"talle": 42, "stock": 3}, {"talle": 43, "stock": 2}], foto: 'Fotos/Deportivas fit black.jpeg' },
  { modelo: 'Ojotas Louis Vuitton negras', talles: [{"talle": 39, "stock": 12}, {"talle": 40, "stock": 12}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 3}, {"talle": 43, "stock": 8}, {"talle": 44, "stock": 8}], foto: 'Fotos/Ojotas Louis Vuitton negras.jpeg' },
  { modelo: 'Adidas forum blanco Preto', talles: [{"talle": 35, "stock": 1}, {"talle": 39, "stock": 1}, {"talle": 40, "stock": 1}], foto: 'Fotos/Adidas forum blanco Preto.jpeg' },
  { modelo: 'Dunk pombo', talles: [{"talle": 42, "stock": 1}, {"talle": 43, "stock": 7}, {"talle": 44, "stock": 3}], foto: 'Fotos/Dunk pombo.jpeg' },
  { modelo: 'Jordan 1 botitas pink', talles: [{"talle": 39, "stock": 3}, {"talle": 40, "stock": 11}], foto: 'Fotos/Jordan 1 botitas pink.jpeg' },
  { modelo: 'Forum adidas celeste', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 7}, {"talle": 38, "stock": 1}], foto: 'Fotos/Forum adidas celeste.jpeg' },
  { modelo: 'Air forcé 1 total black', talles: [{"talle": 34, "stock": 3}, {"talle": 35, "stock": 1}, {"talle": 38, "stock": 1}, {"talle": 43, "stock": 1}], foto: 'Fotos/Air forcé 1 total black.jpeg' },
  { modelo: 'Puma 180 flamingo', talles: [{"talle": 34, "stock": 2}, {"talle": 36, "stock": 1}], foto: 'Fotos/Puma 180 flamingo.jpeg' },
  { modelo: 'Jordan retro 4 pink', talles: [{"talle": 38, "stock": 5}, {"talle": 39, "stock": 5}, {"talle": 40, "stock": 2}], foto: 'Fotos/Jordan retro 4 pink.jpeg' },
  { modelo: 'Jordan retro 4 /total black', talles: [{"talle": 44, "stock": 1}], foto: 'Fotos/Jordan retro 4 total black.jpeg' },
  { modelo: 'Sb Jordan triple black', talles: [{"talle": 39, "stock": 1}, {"talle": 40, "stock": 2}, {"talle": 41, "stock": 1}, {"talle": 42, "stock": 2}, {"talle": 43, "stock": 1}], foto: 'Fotos/Sb Jordan triple black.jpeg' },
  { modelo: 'Air forcé exclusivas white', talles: [{"talle": 43, "stock": 8}, {"talle": 44, "stock": 1}], foto: 'Fotos/Air forcé exclusivas white.jpeg' },
  { modelo: 'NB 530 blanca /azul', talles: [{"talle": 35, "stock": 2}], foto: 'Fotos/NB 530 blanca azul.jpeg' },
  { modelo: 'Jordan 1 verniz', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 4}, {"talle": 37, "stock": 2}, {"talle": 39, "stock": 2}, {"talle": 40, "stock": 1}, {"talle": 41, "stock": 4}, {"talle": 42, "stock": 2}, {"talle": 43, "stock": 4}], foto: 'Fotos/Jordan 1 verniz.jpeg' },
  { modelo: 'Adidas forum Preto blanco', talles: [{"talle": 39, "stock": 2}, {"talle": 40, "stock": 2}, {"talle": 41, "stock": 1}, {"talle": 42, "stock": 1}], foto: 'Fotos/Adidas forum Preto blanco.jpeg' },
  { modelo: 'New balance 9060 suela rosa', talles: [{"talle": 34, "stock": 3}, {"talle": 35, "stock": 6}, {"talle": 36, "stock": 4}, {"talle": 37, "stock": 3}], foto: 'Fotos/New balance 9060 suela rosa.jpeg' },
  { modelo: 'Shox black', talles: [{"talle": 42, "stock": 2}, {"talle": 43, "stock": 4}, {"talle": 44, "stock": 2}], foto: 'Fotos/Shox black.jpeg' },
  { modelo: 'Dunk total black', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 3}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 4}, {"talle": 43, "stock": 1}, {"talle": 44, "stock": 2}], foto: 'Fotos/Dunk total black.jpeg' },
  { modelo: 'Ojotas total black', talles: [{"talle": 37, "stock": 15}, {"talle": 38, "stock": 15}, {"talle": 39, "stock": 83}, {"talle": 40, "stock": 83}, {"talle": 41, "stock": 55}, {"talle": 42, "stock": 55}, {"talle": 43, "stock": 19}, {"talle": 44, "stock": 19}], foto: 'Fotos/Ojotas total black.jpeg' },
  { modelo: 'NB 530 blanca/negro', talles: [{"talle": 34, "stock": 2}, {"talle": 35, "stock": 1}, {"talle": 37, "stock": 1}], foto: 'Fotos/NB 530 blanca negro.jpeg' },
  { modelo: 'Air force Champion', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 1}, {"talle": 42, "stock": 2}, {"talle": 43, "stock": 2}, {"talle": 44, "stock": 1}], foto: 'Fotos/Air force Champion.jpeg' },
  { modelo: 'Dunk glistter celeste', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 1}], foto: 'Fotos/Dunk glistter celeste.jpeg' },
  { modelo: 'Dunk celeste', talles: [{"talle": 38, "stock": 1}], foto: 'Fotos/Dunk celeste.jpeg' },
  { modelo: 'Vans Haylan 01', talles: [{"talle": 35, "stock": 1}, {"talle": 43, "stock": 2}], foto: 'Fotos/Vans Haylan 01.jpeg' },
  { modelo: 'Nike shox white', talles: [{"talle": 41, "stock": 1}, {"talle": 43, "stock": 9}], foto: 'Fotos/Nike shox white.jpeg' },
  { modelo: 'Adidas forum salmon', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 2}, {"talle": 36, "stock": 4}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 2}], foto: 'Fotos/Adidas forum salmon.jpeg' },
  { modelo: 'Dunk glitter rosa', talles: [{"talle": 38, "stock": 1}, {"talle": 40, "stock": 1}], foto: 'Fotos/Dunk glitter rosa.jpeg' },
  { modelo: 'Sb dunk pipa negra', talles: [{"talle": 39, "stock": 2}, {"talle": 40, "stock": 2}, {"talle": 41, "stock": 4}, {"talle": 42, "stock": 3}, {"talle": 43, "stock": 5}, {"talle": 44, "stock": 1}], foto: 'Fotos/Sb dunk pipa negra.jpeg' },
  { modelo: 'Jordan low 1 DIAMOND', talles: [{"talle": 36, "stock": 1}, {"talle": 37, "stock": 9}, {"talle": 38, "stock": 4}, {"talle": 39, "stock": 3}, {"talle": 40, "stock": 2}], foto: 'Fotos/Jordan low 1 DIAMOND.jpeg' },
  { modelo: 'Jordan retro 4 panda', talles: [{"talle": 35, "stock": 3}, {"talle": 36, "stock": 3}, {"talle": 37, "stock": 6}, {"talle": 38, "stock": 6}, {"talle": 39, "stock": 3}, {"talle": 40, "stock": 3}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 2}, {"talle": 43, "stock": 2}], foto: 'Fotos/Jordan retro 4 panda.jpeg' },
  { modelo: 'Mind negras', talles: [{"talle": 41, "stock": 19}, {"talle": 42, "stock": 19}, {"talle": 43, "stock": 17}, {"talle": 44, "stock": 17}], foto: 'Fotos/Mind negras.jpeg' },
  { modelo: 'Air force 1 blanca /pipa gris', talles: [{"talle": 43, "stock": 1}, {"talle": 44, "stock": 1}], foto: 'Fotos/Air force 1 blanca pipa gris.jpeg' },
  { modelo: 'Deportivas fit white', talles: [{"talle": 35, "stock": 1}, {"talle": 37, "stock": 2}, {"talle": 38, "stock": 1}, {"talle": 39, "stock": 2}], foto: 'Fotos/Deportivas fit white.jpeg' },
  { modelo: 'Vans haylan black', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 2}, {"talle": 44, "stock": 1}], foto: 'Fotos/Vans haylan black.jpeg' },
  { modelo: 'Air forcé blanca pipa negra', talles: [{"talle": 34, "stock": 1}, {"talle": 36, "stock": 2}], foto: 'Fotos/Air forcé blanca pipa negra.jpeg' },
  { modelo: 'Mind beige', talles: [{"talle": 41, "stock": 41}, {"talle": 42, "stock": 41}, {"talle": 43, "stock": 41}, {"talle": 44, "stock": 41}], foto: 'Fotos/Mind beige.jpeg' },
  { modelo: 'Vans HAYLAN celestes', talles: [{"talle": 37, "stock": 4}, {"talle": 39, "stock": 3}, {"talle": 40, "stock": 2}], foto: 'Fotos/Vans HAYLAN celestes.jpeg' },
  { modelo: 'Vans Haylan beige', talles: [{"talle": 43, "stock": 3}], foto: 'Fotos/Vans Haylan beige.jpeg' },
  { modelo: 'Samba Classic', talles: [{"talle": 43, "stock": 2}, {"talle": 44, "stock": 1}], foto: 'Fotos/Samba Classic.jpeg' },
  { modelo: 'New balance 9060 suela gris', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 1}, {"talle": 36, "stock": 3}, {"talle": 37, "stock": 1}], foto: 'Fotos/New balance 9060 suela gris.jpeg' },
  { modelo: 'Jordan retro 4 GREEN', talles: [{"talle": 34, "stock": 1}], foto: 'Fotos/Jordan retro 4 GREEN.jpeg' },
  { modelo: 'Air Jordan Pink', talles: [{"talle": 38, "stock": 1}, {"talle": 39, "stock": 2}], foto: 'Fotos/Air Jordan Pink.jpeg' },
  { modelo: 'Jordan low VERNIZ /AZUL', talles: [{"talle": 34, "stock": 3}, {"talle": 35, "stock": 3}, {"talle": 36, "stock": 6}, {"talle": 37, "stock": 6}, {"talle": 38, "stock": 4}, {"talle": 41, "stock": 1}], foto: 'Fotos/Jordan low VERNIZ AZUL.jpeg' },
  { modelo: 'Súper star brillo', talles: [{"talle": 37, "stock": 1}, {"talle": 39, "stock": 5}, {"talle": 40, "stock": 6}, {"talle": 41, "stock": 2}], foto: 'Fotos/Súper star brillo.jpeg' },
  { modelo: 'Jordan 1 café flamingo', talles: [{"talle": 40, "stock": 1}], foto: 'Fotos/Jordan 1 café flamingo.jpeg' },
  { modelo: 'Jordan low brillo', talles: [{"talle": 36, "stock": 1}, {"talle": 37, "stock": 5}, {"talle": 38, "stock": 4}, {"talle": 39, "stock": 5}, {"talle": 40, "stock": 2}], foto: 'Fotos/Jordan low brillo.jpeg' },
  { modelo: 'Super star rosa', talles: [{"talle": 40, "stock": 1}], foto: 'Fotos/Super star rosa.jpeg' },
  { modelo: 'Air Jordan pipa gris', talles: [{"talle": 38, "stock": 1}, {"talle": 39, "stock": 2}, {"talle": 40, "stock": 3}, {"talle": 41, "stock": 5}, {"talle": 42, "stock": 1}, {"talle": 43, "stock": 1}], foto: 'Fotos/Air Jordan pipa gris.jpeg' },
  { modelo: 'TL1 Negras', talles: [{"talle": 38, "stock": 1}], foto: 'Fotos/TL1 Negras.jpeg' },
  { modelo: 'Vans KNU plataforma alta', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 4}, {"talle": 38, "stock": 3}, {"talle": 39, "stock": 3}, {"talle": 40, "stock": 1}], foto: 'Fotos/Vans KNU plataforma alta.jpeg' },
  { modelo: 'Nike V5 rosa', talles: [{"talle": 38, "stock": 1}, {"talle": 39, "stock": 2}, {"talle": 40, "stock": 1}], foto: 'Fotos/Nike V5 rosa.jpeg' },
  { modelo: 'ABZORB negras', talles: [{"talle": 37, "stock": 2}], foto: 'Fotos/ABZORB negras.jpeg' },
  { modelo: 'ABZORB claritas', talles: [{"talle": 34, "stock": 1}], foto: 'Fotos/ABZORB claritas.jpeg' },
  { modelo: 'Sb dunk polar', talles: [{"talle": 36, "stock": 2}, {"talle": 37, "stock": 2}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 2}], foto: 'Fotos/Sb dunk polar.jpeg' },
  { modelo: 'Jordan 1 crema', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 1}, {"talle": 36, "stock": 1}, {"talle": 37, "stock": 1}, {"talle": 39, "stock": 1}], foto: 'Fotos/Jordan 1 crema.jpeg' },
  { modelo: 'Botitas Jordan niño', talles: [{"talle": 26, "stock": 1}], foto: 'Fotos/Botitas Jordan niño.jpeg' },
  { modelo: 'Nb 9060 marron', talles: [{"talle": 36, "stock": 2}], foto: 'Fotos/Nb 9060 marron.jpeg' },
  { modelo: 'Jordan 1 suela celeste', talles: [{"talle": 35, "stock": 1}, {"talle": 37, "stock": 1}, {"talle": 38, "stock": 1}, {"talle": 39, "stock": 2}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 2}, {"talle": 43, "stock": 1}], foto: 'Fotos/Jordan 1 suela celeste.jpeg' },
  { modelo: 'Air forcé celeste tornasol', talles: [{"talle": 38, "stock": 1}], foto: 'Fotos/Air forcé celeste tornasol.jpeg' },
  { modelo: 'Jordan 11 suela celeste', talles: [{"talle": 42, "stock": 1}], foto: 'Fotos/Jordan 11 suela celeste.jpeg' },
  { modelo: 'Samba total black', talles: [{"talle": 36, "stock": 1}], foto: 'Fotos/Samba total black.jpeg' },
  { modelo: 'Adidas samba marron', talles: [{"talle": 39, "stock": 1}], foto: 'Fotos/Adidas samba marron.jpeg' },
  { modelo: 'Nb 530 grafite', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 2}, {"talle": 38, "stock": 1}], foto: 'Fotos/Nb 530 grafite.jpeg' },
  { modelo: 'Air forcé black brillo', talles: [{"talle": 37, "stock": 1}, {"talle": 38, "stock": 1}], foto: 'Fotos/Air forcé black brillo.jpeg' },
  { modelo: 'Nb 4000 blancas', talles: [{"talle": 36, "stock": 1}, {"talle": 37, "stock": 1}], foto: 'Fotos/Nb 4000 blancas.jpeg' },
  { modelo: 'Jordan low glister', talles: [{"talle": 35, "stock": 4}, {"talle": 36, "stock": 4}, {"talle": 37, "stock": 4}, {"talle": 38, "stock": 2}], foto: 'Fotos/Jordan low glister.jpeg' },
  { modelo: 'Adidas 2000 white', talles: [{"talle": 41, "stock": 1}], foto: 'Fotos/Adidas 2000 white.jpeg' },
  { modelo: 'Dunk verde oliva', talles: [{"talle": 43, "stock": 1}], foto: 'Fotos/Dunk verde oliva.jpeg' },
  { modelo: 'Nb ABZORB white', talles: [{"talle": 35, "stock": 3}], foto: 'Fotos/Nb ABZORB white.jpeg' },
  { modelo: 'Vans Haylan grafite', talles: [{"talle": 43, "stock": 2}], foto: 'Fotos/Vans Haylan grafite.jpeg' },
  { modelo: 'Nb 530 marinho nova', talles: [{"talle": 37, "stock": 1}], foto: 'Fotos/Nb 530 marinho nova.jpeg' },
  { modelo: 'Jordan retro 4 black costura', talles: [{"talle": 40, "stock": 1}], foto: 'Fotos/Jordan retro 4 black costura.jpeg' },
];
