const stock_zapatillas = [
  { modelo: 'Air forcé 1 blancas', talles: [{"talle": 38, "stock": 1}, {"talle": 39, "stock": 3}, {"talle": 40, "stock": 3}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 3}, {"talle": 43, "stock": 5}], foto: 'Fotos/Air forcé 1 blancas.jpeg' },
  { modelo: 'Vans KNU clasicas', talles: [{"talle": 34, "stock": 7}, {"talle": 35, "stock": 5}, {"talle": 36, "stock": 4}, {"talle": 38, "stock": 3}, {"talle": 41, "stock": 1}, {"talle": 42, "stock": 2}, {"talle": 43, "stock": 1}], foto: 'Fotos/Vans KNU clasicas.jpeg' },
  { modelo: 'Panda sb dunk', talles: [{"talle": 35, "stock": 3}, {"talle": 37, "stock": 4}, {"talle": 38, "stock": 1}, {"talle": 39, "stock": 3}, {"talle": 40, "stock": 7}, {"talle": 41, "stock": 4}, {"talle": 42, "stock": 2}, {"talle": 43, "stock": 2}, {"talle": 44, "stock": 1}], foto: 'Fotos/Panda sb dunk.jpeg' },
  { modelo: 'Adidas forum blancas', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 6}, {"talle": 36, "stock": 3}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 1}], foto: 'Fotos/Adidas forum blancas.jpeg' },
  { modelo: 'New balance 530 running', talles: [{"talle": 36, "stock": 2}, {"talle": 37, "stock": 1}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 4}, {"talle": 40, "stock": 2}, {"talle": 41, "stock": 1}], foto: 'Fotos/New balance 530 running.jpeg' },
  { modelo: 'Puma 180 WHITE', talles: [{"talle": 35, "stock": 3}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 12}, {"talle": 38, "stock": 12}, {"talle": 39, "stock": 10}, {"talle": 40, "stock": 9}, {"talle": 41, "stock": 6}, {"talle": 42, "stock": 9}, {"talle": 43, "stock": 4}, {"talle": 44, "stock": 3}], foto: 'Fotos/Puma 180 WHITE.jpeg' },
  { modelo: 'Super star black', talles: [{"talle": 36, "stock": 9}, {"talle": 37, "stock": 4}, {"talle": 38, "stock": 6}, {"talle": 39, "stock": 4}, {"talle": 44, "stock": 2}], foto: 'Fotos/Super star black.jpeg' },
  { modelo: 'Super star clásic', talles: [{"talle": 34, "stock": 2}, {"talle": 35, "stock": 2}, {"talle": 36, "stock": 1}, {"talle": 38, "stock": 1}, {"talle": 39, "stock": 2}, {"talle": 40, "stock": 1}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 3}, {"talle": 43, "stock": 3}, {"talle": 44, "stock": 4}], foto: 'Fotos/Super star clásic.jpeg' },
  { modelo: 'Air forcé suela celeste', talles: [{"talle": 41, "stock": 3}, {"talle": 42, "stock": 5}, {"talle": 43, "stock": 3}], foto: 'Fotos/Air forcé suela celeste.jpeg' },
  { modelo: 'Sb dunk gris', talles: [{"talle": 35, "stock": 1}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 4}, {"talle": 39, "stock": 1}, {"talle": 40, "stock": 2}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 3}, {"talle": 43, "stock": 4}], foto: 'Fotos/Sb dunk gris.jpeg' },
  { modelo: 'Adidas forum Gelo', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 2}, {"talle": 36, "stock": 3}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 2}], foto: 'Fotos/Adidas forum Gelo.jpeg' },
  { modelo: 'Dunk bordo', talles: [{"talle": 38, "stock": 4}, {"talle": 39, "stock": 4}], foto: 'Fotos/Dunk bordo.jpeg' },
  { modelo: 'Ojotas Louis Vuitton negras', talles: [{"talle": 39, "stock": 4}, {"talle": 40, "stock": 4}, {"talle": 43, "stock": 7}, {"talle": 44, "stock": 7}], foto: 'Fotos/Ojotas Louis Vuitton negras.jpeg' },
  { modelo: 'Deportivas fit black', talles: [{"talle": 35, "stock": 2}, {"talle": 38, "stock": 1}, {"talle": 40, "stock": 1}, {"talle": 41, "stock": 1}, {"talle": 42, "stock": 1}, {"talle": 43, "stock": 2}], foto: 'Fotos/Deportivas fit black.jpeg' },
  { modelo: 'Adidas forum blanco Preto', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 1}, {"talle": 39, "stock": 2}], foto: 'Fotos/Adidas forum blanco Preto.jpeg' },
  { modelo: 'Jordan retro 4 pintita', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 1}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 3}, {"talle": 39, "stock": 2}, {"talle": 40, "stock": 1}, {"talle": 43, "stock": 3}, {"talle": 44, "stock": 1}], foto: 'Fotos/Jordan retro 4 pintita.jpeg' },
  { modelo: 'Dunk pombo', talles: [{"talle": 42, "stock": 1}, {"talle": 43, "stock": 7}, {"talle": 44, "stock": 2}], foto: 'Fotos/Dunk pombo.jpeg' },
  { modelo: 'Jordan 1 botitas pink', talles: [{"talle": 39, "stock": 1}, {"talle": 40, "stock": 11}], foto: 'Fotos/Jordan 1 botitas pink.jpeg' },
  { modelo: 'Forum adidas celeste', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 3}, {"talle": 37, "stock": 7}, {"talle": 38, "stock": 1}], foto: 'Fotos/Forum adidas celeste.jpeg' },
  { modelo: 'Air forcé 1 total black', talles: [{"talle": 34, "stock": 3}, {"talle": 37, "stock": 1}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 1}, {"talle": 43, "stock": 1}], foto: 'Fotos/Air forcé 1 total black.jpeg' },
  { modelo: 'Puma 180 flamingo', talles: [{"talle": 34, "stock": 2}], foto: 'Fotos/Puma 180 flamingo.jpeg' },
  { modelo: 'Jordan retro 4 pink', talles: [{"talle": 38, "stock": 4}, {"talle": 39, "stock": 5}, {"talle": 40, "stock": 2}], foto: 'Fotos/Jordan retro 4 pink.jpeg' },
  { modelo: 'Jordan retro 4 /total black', talles: [{"talle": 35, "stock": 1}, {"talle": 37, "stock": 1}, {"talle": 42, "stock": 1}, {"talle": 43, "stock": 6}, {"talle": 44, "stock": 4}], foto: 'Fotos/Jordan retro 4 total black.jpeg' },
  { modelo: 'Nb 530 grafite', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 2}, {"talle": 39, "stock": 1}], foto: 'Fotos/Nb 530 grafite.jpeg' },
  { modelo: 'Nb 9060 marron', talles: [{"talle": 36, "stock": 2}], foto: 'Fotos/Nb 9060 marron.jpeg' },
  { modelo: 'Jordan retro 4 caramelo', talles: [{"talle": 39, "stock": 1}, {"talle": 42, "stock": 2}], foto: 'Fotos/Jordan retro 4 caramelo.jpeg' },
  { modelo: 'TL1 blancas', talles: [{"talle": 35, "stock": 1}, {"talle": 37, "stock": 1}], foto: 'Fotos/TL1 blancas.jpeg' },
  { modelo: 'Air forcé black brillo', talles: [{"talle": 37, "stock": 1}, {"talle": 38, "stock": 1}], foto: 'Fotos/Air forcé black brillo.jpeg' },
  { modelo: 'Adidas 2000 royal', talles: [{"talle": 43, "stock": 1}], foto: 'Fotos/Adidas 2000 royal.jpeg' },
  { modelo: 'Nb 530 marinho nova', talles: [{"talle": 38, "stock": 1}], foto: 'Fotos/Nb 530 marinho nova.jpeg' },
  { modelo: 'Air forcé glister rosa', talles: [{"talle": 37, "stock": 2}], foto: 'Fotos/Air forcé glister rosa.jpeg' },
  { modelo: 'Jordan retro 4 doraudo', talles: [{"talle": 36, "stock": 1}, {"talle": 38, "stock": 1}, {"talle": 39, "stock": 1}], foto: 'Fotos/Jordan retro 4 doraudo.jpeg' },
  { modelo: 'Jordan low glister', talles: [{"talle": 35, "stock": 4}, {"talle": 36, "stock": 4}, {"talle": 37, "stock": 4}, {"talle": 38, "stock": 2}], foto: 'Fotos/Jordan low glister.jpeg' },
  { modelo: 'Adidas 2000 white', talles: [{"talle": 41, "stock": 1}], foto: 'Fotos/Adidas 2000 white.jpeg' },
  { modelo: 'Dunk verde oliva', talles: [{"talle": 43, "stock": 1}], foto: 'Fotos/Dunk verde oliva.jpeg' },
  { modelo: 'Nb ABZORB white', talles: [{"talle": 35, "stock": 3}], foto: 'Fotos/Nb ABZORB white.jpeg' },
  { modelo: 'Vans Haylan grafite', talles: [{"talle": 43, "stock": 2}], foto: 'Fotos/Vans Haylan grafite.jpeg' },
  { modelo: 'Nb 9060 celeste', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 1}, {"talle": 37, "stock": 1}], foto: 'Fotos/Nb 9060 celeste.jpeg' },
  { modelo: 'Jordan retro 4 red', talles: [{"talle": 36, "stock": 2}, {"talle": 37, "stock": 2}, {"talle": 38, "stock": 1}], foto: 'Fotos/Jordan retro 4 red.jpeg' },
  { modelo: 'Jordan 1 preto verniz', talles: [{"talle": 35, "stock": 1}, {"talle": 39, "stock": 1}], foto: 'Fotos/Jordan 1 preto verniz.jpeg' },
  { modelo: 'Jordan 1 celeste / verniz', talles: [{"talle": 34, "stock": 1}, {"talle": 36, "stock": 1}, {"talle": 37, "stock": 1}], foto: 'Fotos/Jordan 1 celeste verniz.jpeg' },
  { modelo: 'Puma 180 White/gris', talles: [{"talle": 40, "stock": 2}], foto: 'Fotos/Puma 180 White gris.jpeg' },
  { modelo: 'Jordan retro 4 black/dorado', talles: [{"talle": 40, "stock": 3}], foto: 'Fotos/Jordan retro 4 black dorado.jpeg' },
  { modelo: 'Nike mind gris', talles: [{"talle": 41, "stock": 1}, {"talle": 43, "stock": 2}], foto: 'Fotos/Nike mind gris.jpeg' },
  { modelo: 'Jordan 1 verde / naranja', talles: [{"talle": 41, "stock": 1}, {"talle": 43, "stock": 2}, {"talle": 44, "stock": 1}], foto: 'Fotos/Jordan 1 verde naranja.jpeg' },
  { modelo: 'Sb Dunk VINO', talles: [{"talle": 39, "stock": 1}, {"talle": 40, "stock": 1}, {"talle": 42, "stock": 2}], foto: 'Fotos/Sb Dunk VINO.jpeg' },
  { modelo: 'Air forcé blanca brillo', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 4}, {"talle": 37, "stock": 2}, {"talle": 38, "stock": 5}, {"talle": 39, "stock": 3}, {"talle": 40, "stock": 2}], foto: 'Fotos/Air forcé blanca brillo.jpeg' },
  { modelo: 'Nb 9060 marrón nova', talles: [{"talle": 34, "stock": 2}, {"talle": 35, "stock": 6}, {"talle": 36, "stock": 8}, {"talle": 37, "stock": 6}, {"talle": 38, "stock": 6}, {"talle": 39, "stock": 3}, {"talle": 40, "stock": 4}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 1}, {"talle": 43, "stock": 2}], foto: 'Fotos/Nb 9060 marrón nova.jpeg' },
  { modelo: 'Nb 9060 black', talles: [{"talle": 36, "stock": 3}, {"talle": 37, "stock": 1}, {"talle": 38, "stock": 2}], foto: 'Fotos/Nb 9060 black.jpeg' },
  { modelo: 'Jordan retro 1 vérmelo', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 1}, {"talle": 38, "stock": 2}], foto: 'Fotos/Jordan retro 1 vérmelo.jpeg' },
  { modelo: 'Vans Haylan tira gris', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 1}, {"talle": 38, "stock": 2}], foto: 'Fotos/Vans Haylan tira gris.jpeg' },
  { modelo: 'Jordan 1 beige tornasol', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 2}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 1}], foto: 'Fotos/Jordan 1 beige tornasol.jpeg' },
  { modelo: 'Nike v2K', talles: [{"talle": 34, "stock": 2}, {"talle": 35, "stock": 6}, {"talle": 36, "stock": 8}, {"talle": 37, "stock": 7}, {"talle": 38, "stock": 3}], foto: 'Fotos/Nike v2K.jpeg' },
  { modelo: 'Super star dorado', talles: [{"talle": 36, "stock": 2}, {"talle": 38, "stock": 3}, {"talle": 39, "stock": 2}], foto: 'Fotos/Super star dorado.jpeg' },
  { modelo: 'Súper star total black', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 1}, {"talle": 38, "stock": 1}, {"talle": 39, "stock": 1}, {"talle": 40, "stock": 1}], foto: 'Fotos/Súper star total black.jpeg' },
  { modelo: 'Samba beige', talles: [{"talle": 36, "stock": 2}, {"talle": 37, "stock": 1}, {"talle": 38, "stock": 1}, {"talle": 39, "stock": 2}], foto: 'Fotos/Samba beige.jpeg' },
  { modelo: 'Dunk panda azul', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 1}, {"talle": 37, "stock": 2}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 3}, {"talle": 40, "stock": 3}, {"talle": 41, "stock": 2}, {"talle": 42, "stock": 2}, {"talle": 43, "stock": 2}, {"talle": 44, "stock": 1}], foto: 'Fotos/Dunk panda azul.jpeg' },
  { modelo: 'Low preto brillo', talles: [{"talle": 37, "stock": 3}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 2}], foto: 'Fotos/Low preto brillo.jpeg' },
  { modelo: 'Campus gris', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 2}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 1}], foto: 'Fotos/Campus gris.jpeg' },
  { modelo: 'Air forcé tela rosa', talles: [{"talle": 34, "stock": 3}, {"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 2}], foto: 'Fotos/Air forcé tela rosa.jpeg' },
  { modelo: 'Jordan 1 bordo/rosa', talles: [{"talle": 35, "stock": 2}, {"talle": 36, "stock": 1}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 2}, {"talle": 39, "stock": 1}], foto: 'Fotos/Jordan 1 bordo rosa.jpeg' },
  { modelo: 'NB celeste 9060', talles: [{"talle": 35, "stock": 1}], foto: 'Fotos/NB celeste 9060.jpeg' },
  { modelo: 'Nb 9060 begee', talles: [{"talle": 34, "stock": 1}, {"talle": 35, "stock": 3}, {"talle": 36, "stock": 4}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 1}], foto: 'Fotos/Nb 9060 begee.jpeg' },
  { modelo: 'Samba marron', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 2}, {"talle": 38, "stock": 3}, {"talle": 39, "stock": 1}], foto: 'Fotos/Samba marron.jpeg' },
  { modelo: 'Dunk verde', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 1}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 3}, {"talle": 39, "stock": 2}], foto: 'Fotos/Dunk verde.jpeg' },
  { modelo: 'Jordan retro 4 RED', talles: [{"talle": 38, "stock": 1}, {"talle": 39, "stock": 2}, {"talle": 40, "stock": 3}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 1}, {"talle": 43, "stock": 1}], foto: 'Fotos/Jordan retro 4 RED.jpeg' },
  { modelo: 'Jordan retro 4 gris', talles: [{"talle": 36, "stock": 2}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 3}, {"talle": 39, "stock": 2}, {"talle": 40, "stock": 1}], foto: 'Fotos/Jordan retro 4 gris.jpeg' },
  { modelo: 'Forum gris Qualida', talles: [{"talle": 39, "stock": 1}, {"talle": 40, "stock": 2}, {"talle": 41, "stock": 3}, {"talle": 42, "stock": 3}, {"talle": 43, "stock": 2}, {"talle": 44, "stock": 1}], foto: 'Fotos/Forum gris Qualida.jpeg' },
  { modelo: 'Samba azul', talles: [{"talle": 35, "stock": 1}, {"talle": 36, "stock": 2}, {"talle": 37, "stock": 3}, {"talle": 38, "stock": 3}, {"talle": 39, "stock": 2}, {"talle": 40, "stock": 1}], foto: 'Fotos/Samba azul.jpeg' },
];
